# Generated by Django 5.0.2 on 2024-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_solicitudcompra_solicitudproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcompra',
            name='pago',
            field=models.DateField(),
        ),
    ]
