# Generated by Django 5.0.2 on 2024-07-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_solicitudcompra_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='total',
        ),
    ]
