# Generated by Django 5.0.2 on 2024-07-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_solicitudcompra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcompra',
            name='productos',
            field=models.ManyToManyField(blank=True, through='api.SolicitudProducto', to='api.catalogue'),
        ),
        migrations.AlterField(
            model_name='solicitudproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
